### PR TITLE
Adapter.replace, one-to-one only

### PR DESCRIPTION
**Pull request by dhilt**
For issue #171.

### CODE REVIEW

**Comment by duxor** [comment]
We definitely need this. Replacement with "remove + insert" has an issue if we work with elements in the viewport.

**Comment by dhilt** [comment]
@duxor Hi! At least 1-2 weeks are needed to complete the in-viewport many-to-many replacement feature. But one-to-one replacement is already done, and if you need it, I can release ngx-ui-scroll v1.11.0-rc

**Comment by duxor** [comment]
Hi @dhilt 
It should be great, please do it, thanks.

**Comment by dhilt** [comment]
@duxor ngx-ui-scroll v1.11.0-rc is on npm, it has basic `Adapter.replace` implementation. The syntax as follows:

```
datasource.adapter.replace({
  predicate: ({ $index, data, element }) => $index === indexToReplace,
  items: [itemToReplace]
})
```

Note, `predicate` must return `true` no more than 1 time, `items` must contain only 1 item. Would be great to get any feedback on this!

**Comment by duxor** [comment]
@dhilt awesome! Works as expected, thanks.

**Pull request merged**
